// constants/proposalConstants.js
export const API_BASE_URL = 'http://127.0.0.1:5000/api';

export const SECTION_TITLES = {
  PROJECT_PROFILE: 'I. PROJECT PROFILE',
  RATIONALE: 'II. RATIONALE',
  SIGNIFICANCE: 'III. SIGNIFICANCE',
  OBJECTIVES: 'IV. OBJECTIVES',
  METHODOLOGY: 'V. METHODOLOGY',
  EXPECTED_OUTPUT: 'VI. EXPECTED OUTPUT/OUTCOME',
  SUSTAINABILITY: 'VII. SUSTAINABILITY PLAN',
  ORGANIZATION: 'VIII. ORGANIZATION AND STAFFING',
  PLAN_OF_ACTIVITIES: 'IX. PLAN OF ACTIVITIES',
  BUDGETARY: 'XI. BUDGETARY REQUIREMENT',
};

export const BUDGET_CATEGORIES = {
  MEALS: 'meals',
  TRANSPORT: 'transport',
  SUPPLIES: 'supplies',
};

export const STATUS = {
  CURRENT: 'current',
  HISTORY: 'history',
};